use serde::Serialize;

use crate::{auth::{config::{AuthConfig, Entity, FederationEntity, UserEntity}, password::HashedPassword}, model::EntityName};

#[derive(Debug, Serialize, Default)]
pub struct PartialConfig {
    auth: AuthConfig,
}

pub fn serialize_new_entity(name: &EntityName, password: HashedPassword, federation: bool) -> anyhow::Result<String> {
    let mut config = PartialConfig::default();

    let entity = if federation {
        Entity::Federation(FederationEntity { name: name.clone(), password, has_full_image_access: false })
    } else {
        Entity::User(UserEntity { name: name.clone(), password, has_full_image_access: false })
    };

    config.auth.entities.insert(name.clone(), entity);

    let config_content = toml::to_string(&config)?.trim().to_string();
    let now = chrono::Local::now().to_rfc3339();
    let notice = format!("Generated by iris CLI at {now}");

    Ok(format!("# vvv {notice}\n{config_content}\n# ^^^ {notice}"))
}

