use serde::Serialize;

use crate::auth::{config::{AuthConfig, Entity, UserEntity}, password::HashedPassword};

#[derive(Debug, Serialize, Default)]
pub struct PartialConfig {
    auth: AuthConfig,
}

pub fn serialize_new_user(name: &str, password: HashedPassword) -> anyhow::Result<String> {
    let mut config = PartialConfig::default();

    config.auth.entities.insert(
        name.to_string(),
        Entity::User(UserEntity { password })
    );

    let config_content = toml::to_string(&config)?.trim().to_string();
    let now = chrono::Local::now().to_rfc3339();
    let notice = format!("Generated by iris CLI at {now}");

    Ok(format!("# vvv {notice}\n{config_content}\n# ^^^ {notice}"))
}

