on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repos
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Log in to Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Rust build artifact
        uses: Swatinem/rust-cache@v2

      - name: Build Rust project
        run: cargo build --release

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294  # v7.0.0
        with:
          context: .github/workflows/
          push: true
          tags: |
            ghcr.io/pastel-biota/iris:${{ github.ref_name }}
            ghcr.io/pastel-biota/iris:latest

      - name: Attach binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/iris
